name: TEST Release

on:
  pull_request:
    branches: [ main ]

jobs:
  helm:
    permissions:
      contents: read
      packages: write
    uses: joeckr/ci-templates/.github/workflows/push-helm-ghcr.yml@c08d40f0bf0cd80de6b2f1fa2f018f944265b807 # v1.8.0
    with:
      charts-dir: 'charts'
      dry-run: true
  release:
    permissions:
      contents: write
    uses: joeckr/ci-templates/.github/workflows/semantic.yml@48916bb3c57520fe2d7b179ac228b29b0d1c83cb # v1.3.0
    with:
      dry-run: true
